[package]
license = ["Apache-2.0"]
keywords = ["IT Operations/Authentication", "Cost/Freemium"]
org = "ballerinax"
name = "trigger.asgardeo"
repository = "https://github.com/ballerina-platform/asyncapi-triggers"
version = "0.1.1"
distribution = "2201.1.1"
# icon = "docs/icon.png" // commenting this temporarily, since there is a bug in Ballerina DEV central, can't push modules with icons
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
