[package]
license = ["Apache-2.0"]
keywords = ["Communication/Team Chat", "Cost/Freemium"]
org = "hasithaathukorala"
name = "trigger.asgardeo"
icon = "icon.png"
repository = "https://github.com/ballerina-platform/asyncapi-triggers"
version = "0.6.7"
distribution = "2201.0.1"
icon = "docs/icon.png"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
