name: Prod Release

on:
  workflow_dispatch:
    inputs:
      specific_trigger:
        description: Specific Trigger to Release
        required: false

jobs:
  container:
    runs-on: ubuntu-latest
    container:
      image: ballerina/ballerina:2201.2.1
      options: --user root
    steps:
      - name: Install Git
        run: apk --no-cache add git
      - uses: actions/checkout@v2
      - name: Build with Gradle
        env:
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}
          JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true
          packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
          packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
        run: |
          ./gradlew build -Prelease=true -Ptrigger=${{ github.event.inputs.specific_trigger }}
